### ISSUE TITLE
Database?

### ISSUE THREAD

**Issue by araoxervmon** [anchal20/ForTheLoveOfCricket#1]
@anchal20:  What is those headers doing? did you forget to upload a database or is it just a static app?

**Comment by anchal20** [comment]
@araoxervmon: it is just a static app for now. Started with an intention of a complete app but didn't find time to complete it.

**Comment by araoxervmon** [comment]
@anchal20  okay, I thought you missed the database. Let me fork it and play around with it. 
Happy coding

**Comment by anchal20** [comment]
@araoxervmon: Thanks...Enjoy!!
